#!/bin/sh
## /etc/grub.d/90-debian-iso
## Create grub boot menu entries for each Debian netinstall ISO in /boot

## TODO pull network config from current or /etc/network/interfaces
##   and store as kernel cmdline options:
## Installer can pull DHCP, but installed system needs
## network at initramfs stage, for dropbear cryptoroot remote unlock

for iso in /boot/*.iso; do 
  menu="Debian ISO: ${iso##*/}"
  cat <<__END__

menuentry "$menu" {
  loopback iso $iso
  linux (iso)/install.amd/vmlinuz vga=788 \
    auto=true file=/boot/d-i/stretch/preseed.cfg DEBCONF_DEBUG=5 \
    -- quiet
  initrd (iso)/install.amd/initrd.gz
}

__END__
done

sed "s/^\(GRUB_DEFAULT=\).*$/\1\"$menu\"/" /etc/default/grub > /tmp/grub
cat /tmp/grub > /etc/default/grub

