#!/bin/sh
## /etc/grub.d/90-debian-iso
## Create grub boot menu entries for each Debian netinstall ISO in /boot

# sets $dev, $src, and $via
eval x=$(ip ro get 8.8.8.8 | sed 's/\([a-z]\)\s\+/\1=/g')
# sets $inet, $netmask, $broadcast
eval $(ifconfig $dev | grep netmask | sed 's/\([a-z]\)\s\+/\1=/g')

for iso in /boot/*.iso; do 
  menu="Debian ISO: ${iso##*/}"
  cat <<__END__

menuentry "$menu" {
  loopback iso $iso
  linux (iso)/install.amd/vmlinuz vga=788 \
    auto=true file=/boot/d-i/stretch/preseed.cfg \
    interface=$dev netcfg/get_ipaddress=$src netcfg/get_netmask=$netmask \
    netcfg/get_gateway=$via \
    DEBCONF_DEBUG=5 \
    -- quiet
  initrd (iso)/install.amd/initrd.gz
}

__END__
done

sed "s/^\(GRUB_DEFAULT=\).*$/\1\"$menu\"/" /etc/default/grub > /tmp/grub
cat /tmp/grub > /etc/default/grub

