#!/bin/sh
## /etc/grub.d/90-netinstall
## Create grub boot menu entry for Debian netinstall

dir="/boot/d-i"
preseed="url=d-i.seanho.com"
menu="Debian netinstall"

# sets $dev, $src, and $via
eval x=$(ip ro get 8.8.8.8 | sed 's/\([a-z]\)\s\+/\1=/g')
# sets $inet, $netmask, $broadcast
eval $(ifconfig $dev | grep netmask | sed 's/\([a-z]\)\s\+/\1=/g')

# Print GRUB menu entry
cat <<__END__
menuentry "$menu" {
  linux $dir/linux vga=788 auto=true $preseed \
    interface=$dev netcfg/get_ipaddress=$src netcfg/get_netmask=$netmask \
    netcfg/get_gateway=$via \
    DEBCONF_DEBUG=5 -- quiet
  initrd $dir/initrd.gz
}
__END__

# Set as default boot entry
sed "s/^\(GRUB_DEFAULT=\).*$/\1\"$menu\"/" /etc/default/grub > /tmp/grub
cat /tmp/grub > /etc/default/grub

